openapi: 3.0.3
info:
  title: GARA Backend API - Image Listing Extension
  description: |
    Extension to the GARA Backend API to support image listing functionality.
    This specification defines the required endpoint for the frontend to list
    all uploaded images when using backend-based storage mode.
  version: 1.0.0
  contact:
    name: GARA Frontend Team
    url: https://github.com/anhydrous99/gara-frontend

servers:
  - url: http://localhost:8080
    description: Local development server
  - url: https://api.example.com
    description: Production server

paths:
  /api/images:
    get:
      summary: List all uploaded images
      description: |
        Retrieve a paginated list of all uploaded images with their metadata.
        This endpoint is required for the gallery view to display available images.
        Returns image IDs, presigned S3 URLs, and metadata for all images in the system.
      operationId: listImages
      tags:
        - Images
      parameters:
        - name: limit
          in: query
          required: false
          description: Maximum number of images to return (pagination)
          schema:
            type: integer
            minimum: 1
            maximum: 1000
            default: 100
          example: 50
        - name: offset
          in: query
          required: false
          description: Number of images to skip (pagination)
          schema:
            type: integer
            minimum: 0
            default: 0
          example: 0
        - name: sort
          in: query
          required: false
          description: Sort order for results
          schema:
            type: string
            enum: [newest, oldest, name_asc, name_desc]
            default: newest
          example: newest
      responses:
        '200':
          description: List of images retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImageListResponse'
              examples:
                success:
                  summary: Successful response with two images
                  value:
                    images:
                      - id: "a3b5c7d9e1f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4d6e8f0a2b4"
                        name: "sunset-beach"
                        url: "https://gara-images.s3.amazonaws.com/raw/a3b5c7d9...?X-Amz-Signature=..."
                        uploadedAt: "2025-11-17T14:30:00.000Z"
                        size: 2458624
                        format: "jpeg"
                        width: 1920
                        height: 1080
                      - id: "b4c6d8e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4d6e8f0a2b4c6"
                        name: "mountain-landscape"
                        url: "https://gara-images.s3.amazonaws.com/raw/b4c6d8e0...?X-Amz-Signature=..."
                        uploadedAt: "2025-11-17T15:45:00.000Z"
                        size: 3145728
                        format: "png"
                        width: 2560
                        height: 1440
                    total: 247
                    limit: 100
                    offset: 0
                empty:
                  summary: Empty response when no images exist
                  value:
                    images: []
                    total: 0
                    limit: 100
                    offset: 0
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Invalid limit parameter: must be between 1 and 1000"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Failed to retrieve image list from S3"

components:
  schemas:
    ImageListResponse:
      type: object
      required:
        - images
        - total
        - limit
        - offset
      properties:
        images:
          type: array
          description: Array of image metadata objects
          items:
            $ref: '#/components/schemas/ImageMetadata'
        total:
          type: integer
          description: Total number of images available (for pagination)
          example: 247
        limit:
          type: integer
          description: Maximum results returned in this response
          example: 100
        offset:
          type: integer
          description: Number of results skipped
          example: 0

    ImageMetadata:
      type: object
      required:
        - id
        - name
        - url
        - uploadedAt
      properties:
        id:
          type: string
          description: The unique image ID (SHA256 hash of the image content)
          pattern: '^[a-f0-9]{64}$'
          example: "a3b5c7d9e1f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4d6e8f0a2b4"
        name:
          type: string
          description: Original filename without extension
          example: "sunset-beach"
        url:
          type: string
          format: uri
          description: Presigned S3 URL for the original image (valid for 1 hour)
          example: "https://gara-images.s3.amazonaws.com/raw/a3b5c7d9...?X-Amz-Signature=..."
        uploadedAt:
          type: string
          format: date-time
          description: ISO 8601 timestamp of when the image was uploaded
          example: "2025-11-17T14:30:00.000Z"
        size:
          type: integer
          format: int64
          description: File size in bytes
          minimum: 1
          example: 2458624
        format:
          type: string
          description: Original image format
          enum: [jpeg, jpg, png, gif, tiff, webp]
          example: "jpeg"
        width:
          type: integer
          description: Original image width in pixels
          minimum: 1
          example: 1920
        height:
          type: integer
          description: Original image height in pixels
          minimum: 1
          example: 1080

    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Human-readable error message
          example: "Failed to retrieve image list"
        details:
          type: object
          description: Additional error details (optional)
          additionalProperties: true

tags:
  - name: Images
    description: Image management operations
